name: tensorflow
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  # - gensim=3.4.0
  # - s3transfer=0.1.13
  # - smart_open=1.6.0
  # - bzip2=1.0.6
  # - gettext=0.19.8.1
  # - giflib=5.1.4
  # - glib=2.51.4
  # - libiconv=1.15
  # - libpng=1.6.28
  # - libtiff=4.0.7
  # - alabaster=0.7.10
  # - babel=2.5.3
  # - blas=1.0
  # - cryptography=2.2.2
  # - gmp=6.1.2
  # - hdf5=1.10.2
  # - html5lib=1.0.1
  # - idna=2.6
  # - imagesize=1.0.0
  # - intel-openmp=2018.0.3
  # - ipykernel=4.8.2
  # - ipython=6.3.1
  # - ipython_genutils=0.2.0
  # - jedi=0.12.0
  # - jupyter_client=5.2.3
  # - jupyter_core=4.4.0
  # - lazy-object-proxy=1.3.1
  # - libedit=3.1
  # - markupsafe=1.0
  # - ncurses=6.0
  # - numpy=1.14.5
  # - numpy-base=1.14.5
  # - numpydoc=0.8.0
  # - opencv=3.4.1
  # - packaging=17.1
  # - pandoc=1.19.2.1
  # - pandocfilters=1.4.2
  # - parso=0.2.0
  # - pexpect=4.5.0
  # - pickleshare=0.7.4
  # - pip=9.0.1
  # - pygments=2.2.0
  # - pylint=1.8.4
  # - pyopenssl=17.5.0
  # - pyparsing=2.2.0
  # - pyqt=5.6.0
  # - python=3.5.4
  # - pytz=2018.4
  # - pyzmq=17.0.0
  # - scikit-learn=0.19.1
  # - scipy=1.1.0
  # - setuptools=38.4.0
  # - simplegeneric=0.8.1
  # - sip=4.18.1
  # - six=1.11.0
  # - snowballstemmer=1.2.1
  # - sphinx=1.7.3
  # - spyder=3.2.6
  # - wheel=0.30.0
  # - wrapt=1.10.11
  # - xz=5.2.3
  # - zeromq=4.2.5
  # - zlib=1.2.11
  # - pip:
  #   - beautifulsoup4==4.6.0
  #   - bs4==0.0.1
  #   - cython==0.27.3
  #   - h5py==2.7.1
  #   - keras==2.1.6
  #   - nltk==3.3
  #   - pandas==0.23.0
  #   - pyyaml==3.12
  #   - tensorflow==1.12.0
    - flask==1.0.2
prefix: /home/nathan/anaconda2/envs/tensorflow
